// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/truc/truc.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint32                 `protobuf:"varint,17,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest2) Reset() {
	*x = HelloRequest2{}
	mi := &file_proto_truc_truc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest2) ProtoMessage() {}

func (x *HelloRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_truc_truc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest2.ProtoReflect.Descriptor instead.
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return file_proto_truc_truc_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest2) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_proto_truc_truc_proto protoreflect.FileDescriptor

const file_proto_truc_truc_proto_rawDesc = "" +
	"\n" +
	"\x15proto/truc/truc.proto\x12\x05hello\"5\n" +
	"\rHelloRequest2\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x11 \x01(\rR\x03ageB<Z:github.com/davidyannick86/dyt-grpc-proto/protogen/go/hellob\x06proto3"

var (
	file_proto_truc_truc_proto_rawDescOnce sync.Once
	file_proto_truc_truc_proto_rawDescData []byte
)

func file_proto_truc_truc_proto_rawDescGZIP() []byte {
	file_proto_truc_truc_proto_rawDescOnce.Do(func() {
		file_proto_truc_truc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_truc_truc_proto_rawDesc), len(file_proto_truc_truc_proto_rawDesc)))
	})
	return file_proto_truc_truc_proto_rawDescData
}

var file_proto_truc_truc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_truc_truc_proto_goTypes = []any{
	(*HelloRequest2)(nil), // 0: hello.HelloRequest2
}
var file_proto_truc_truc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_truc_truc_proto_init() }
func file_proto_truc_truc_proto_init() {
	if File_proto_truc_truc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_truc_truc_proto_rawDesc), len(file_proto_truc_truc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_truc_truc_proto_goTypes,
		DependencyIndexes: file_proto_truc_truc_proto_depIdxs,
		MessageInfos:      file_proto_truc_truc_proto_msgTypes,
	}.Build()
	File_proto_truc_truc_proto = out.File
	file_proto_truc_truc_proto_goTypes = nil
	file_proto_truc_truc_proto_depIdxs = nil
}
